//! The `--settings` file Claude is launched with: omni's status hooks merged
//! with hcom's bus hooks (so status updates and message delivery both run), plus
//! hcom's env and permission allow-list. Ported from the Go up.go merge; hcom's
//! part is generated by the real `hcom hooks add` so it never drifts.

use anyhow::Result;
use serde_json::{json, Map, Value};
use std::path::PathBuf;

pub fn write_settings(omni_bin: &str) -> Result<PathBuf> {
    let hcom = hcom_settings().unwrap_or_else(|| json!({}));
    let merged = build_settings(omni_bin, &hcom);
    let dir = crate::db::db_path()
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| dirs::home_dir().unwrap_or_default().join(".omni"));
    std::fs::create_dir_all(&dir)?;
    let p = dir.join("hooks.json");
    std::fs::write(&p, serde_json::to_vec_pretty(&merged)?)?;
    Ok(p)
}

/// hcom_settings runs the real `hcom hooks add claude` into a throwaway dir and
/// reads the generated settings (hooks/env/permissions). None if hcom is absent.
fn hcom_settings() -> Option<Value> {
    let tmp = std::env::temp_dir().join(format!("omni-hcom-{}", std::process::id()));
    let hcom_dir = tmp.join(".hcom");
    std::fs::create_dir_all(&hcom_dir).ok()?;
    let out = std::process::Command::new("hcom")
        .args(["hooks", "add", "claude"])
        .env("HCOM_DIR", &hcom_dir)
        .output()
        .ok()?;
    let res = if out.status.success() {
        std::fs::read_to_string(tmp.join(".claude").join("settings.json"))
            .ok()
            .and_then(|t| serde_json::from_str(&t).ok())
    } else {
        None
    };
    let _ = std::fs::remove_dir_all(&tmp);
    res
}

fn build_settings(omni_bin: &str, hcom: &Value) -> Value {
    let cmd_entry = |verb: &str| json!({"hooks":[{"type":"command","command":format!("{} hook {}", omni_bin, verb)}]});
    let omni_hooks = [
        ("SessionStart", "sessionstart"),
        ("PreToolUse", "pre"),
        ("Notification", "notify"),
        ("Stop", "stop"),
        ("SessionEnd", "end"),
    ];
    let mut hooks: Map<String, Value> = Map::new();
    if let Some(h) = hcom.get("hooks").and_then(|v| v.as_object()) {
        for (k, v) in h {
            hooks.insert(k.clone(), v.clone());
        }
    }
    // Drop hcom's Stop hook (`hcom poll`): on idle it long-polls the bus for the
    // configured timeout, and hcom ignores HCOM_TIMEOUT for PTY-hosted agents (our
    // tiles), so it blocks the prompt for the 24h config default — the tile never
    // frees for typing. omni tiles are human-driven and interactive-first: an idle
    // agent shouldn't hold its turn open. Messages still arrive mid-work via the
    // PostToolUse hook, and anything pending is delivered on the next prompt
    // (UserPromptSubmit), so nothing is lost — the agent just doesn't auto-react
    // while idle. omni's own Stop status hook is added below.
    hooks.remove("Stop");
    // prepend omni's status hook so it runs before hcom's bus delivery
    for (ev, verb) in omni_hooks {
        let existing = hooks.get(ev).and_then(|v| v.as_array()).cloned().unwrap_or_default();
        let mut arr = vec![cmd_entry(verb)];
        arr.extend(existing);
        hooks.insert(ev.to_string(), Value::Array(arr));
    }
    let mut settings: Map<String, Value> = Map::new();
    settings.insert("hooks".into(), Value::Object(hooks));
    if let Some(env) = hcom.get("env") {
        settings.insert("env".into(), env.clone());
    }
    if let Some(perms) = hcom.get("permissions") {
        settings.insert("permissions".into(), perms.clone());
    }
    Value::Object(settings)
}

#[cfg(test)]
mod tests {
    use super::*;

    // The merge drops hcom's long-polling Stop hook (it blocks the tile) but keeps
    // omni's own Stop status hook and every other hcom hook (e.g. PostToolUse).
    #[test]
    fn merge_drops_hcom_stop_poll_keeps_the_rest() {
        let hcom = json!({
            "hooks": {
                "Stop": [{"hooks": [{"type": "command", "command": "hcom poll"}]}],
                "PostToolUse": [{"hooks": [{"type": "command", "command": "hcom post"}]}],
            }
        });
        let merged = build_settings("/bin/omni", &hcom);
        let s = serde_json::to_string(&merged["hooks"]).unwrap();
        let stop = merged["hooks"]["Stop"].to_string();
        assert!(stop.contains("/bin/omni hook stop"), "omni Stop hook kept: {stop}");
        assert!(!stop.contains("poll"), "hcom poll dropped from Stop: {stop}");
        assert!(s.contains("hcom post"), "other hcom hooks preserved: {s}");
    }
}
